# Generated by Django 5.2.12 on 2026-03-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres e-mail')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Temat')),
                ('message', models.TextField(verbose_name='Treść wiadomości')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data wysłania')),
                ('is_read', models.BooleanField(default=False, verbose_name='Przeczytane')),
            ],
            options={
                'verbose_name': 'Wiadomość z formularza',
                'verbose_name_plural': 'Wiadomości z formularza',
                'ordering': ['-created_at'],
            },
        ),
    ]
