# Generated by Django 5.2.12 on 2026-03-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collections_title', models.CharField(default='Odkryj więcej sztuki, magii i wiedzy.', max_length=200, verbose_name='Tytuł (Sekcja Kolekcje)')),
                ('collections_text', models.TextField(default='Znajdziesz tu wszystko – od ilustracji, przez plany lekcji norweskiego, aż po sesje Tarota.', verbose_name='Tekst (Sekcja Kolekcje)')),
                ('collections_btn_text', models.CharField(default='Przeglądaj sklep', max_length=100, verbose_name='Tekst na przycisku')),
                ('collections_image', models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Zdjęcie poglądowe (Sekcja Kolekcje)')),
                ('about_title', models.CharField(default='Cześć!', max_length=200, verbose_name='Tytuł (Sekcja O mnie)')),
                ('about_text', models.TextField(default='Tworzę sztukę, magiczne i lingwistyczne materiały oraz pomagam w odkrywaniu siebie poprzez numerologię i Tarota. Chcę dzielić się z Wami moim światem.', verbose_name='Tekst (Sekcja O mnie)')),
                ('about_btn_text', models.CharField(default='Poznaj moją historię', max_length=100, verbose_name='Tekst na przycisku')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Zdjęcie / Portret (Sekcja O mnie)')),
            ],
            options={
                'verbose_name': 'Treść Strony Głównej',
                'verbose_name_plural': 'Treść Strony Głównej',
            },
        ),
    ]
