# Generated by Django 5.2.12 on 2026-03-27 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nazwa usługi')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL (Slug)')),
                ('service_type', models.CharField(choices=[('TAROT', 'Czytanie Tarota'), ('WORKSHOP', 'Warsztat Artystyczny'), ('NUMEROLOGY', 'Analiza Numerologiczna'), ('OTHER', 'Inne')], default='TAROT', max_length=20, verbose_name='Typ usługi')),
                ('description', models.TextField(verbose_name='Opis usługi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Np. 60 dla godzinnej sesji', verbose_name='Czas trwania (minuty)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Zdjęcie poglądowe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna (wyświetlaj na stronie)')),
            ],
            options={
                'verbose_name': 'Usługa',
                'verbose_name_plural': 'Usługi',
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Imię klienta')),
                ('client_email', models.EmailField(max_length=254, verbose_name='E-mail klienta')),
                ('message', models.TextField(blank=True, verbose_name='Wiadomość / Oczekiwania (np. temat do tarota)')),
                ('requested_date', models.DateTimeField(blank=True, null=True, verbose_name='Proponowany termin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data wysłania zapytania')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Obsłużone (odznacz, gdy odpiszesz)')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='services.service', verbose_name='Dotyczy usługi')),
            ],
            options={
                'verbose_name': 'Zapytanie o rezerwację',
                'verbose_name_plural': 'Zapytania o rezerwacje',
                'ordering': ['-created_at'],
            },
        ),
    ]
