# Generated by Django 5.2.12 on 2026-03-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data i czas wydarzenia (zostaw puste dla usług ciągłych)'),
        ),
    ]
