# Generated by Django 5.2.12 on 2026-03-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarotSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł sekcji (np. Zwierciadło Twojej Duszy)')),
                ('description', models.TextField(verbose_name='Treść opisu')),
                ('image', models.ImageField(upload_to='tarot_sections/', verbose_name='Zdjęcie')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność wyświetlania (1, 2, 3...)')),
            ],
            options={
                'verbose_name': 'Sekcja Opisowa Tarota',
                'verbose_name_plural': 'Sekcje Opisowe Tarota',
                'ordering': ['order'],
            },
        ),
    ]
