# Generated by Django 5.2.12 on 2026-03-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_tarotsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa typu (np. Czytanie Tarota)')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Typ usługi',
                'verbose_name_plural': 'Typy usług',
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
    ]
