# Generated by Django 5.2.12 on 2026-03-31 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicetype_remove_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicetype', verbose_name='Typ usługi'),
        ),
    ]
