# Generated by Django 5.2.12 on 2026-03-27 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa kategorii')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL (Slug)')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa produktu')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL (Slug)')),
                ('description', models.TextField(verbose_name='Opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Zdjęcie produktu')),
                ('is_digital', models.BooleanField(default=False, verbose_name='Produkt cyfrowy (nie wymaga wysyłki)')),
                ('digital_file', models.FileField(blank=True, null=True, upload_to='digital_products/', verbose_name='Plik do pobrania (np. PDF)')),
                ('available', models.BooleanField(default=True, verbose_name='Dostępny w sprzedaży')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ostatnia aktualizacja')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
                'ordering': ['-created_at'],
            },
        ),
    ]
