# Generated by Django 5.2.12 on 2026-03-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='digital_file',
        ),
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='products/files/', verbose_name='Plik cyfrowy (np. PDF)'),
        ),
    ]
