# Generated by Django 5.2.12 on 2026-03-30 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail (do wysyłki PDF)')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Ulica i nr domu')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Kod pocztowy')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Miasto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('paid', models.BooleanField(default=False, verbose_name='Opłacone')),
                ('stripe_id', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Zamówienie',
                'verbose_name_plural': 'Zamówienia',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Ilość')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
        ),
    ]
