# Generated by Django 5.2.12 on 2026-03-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(default='kontakt@twojeatelier.pl', max_length=254, verbose_name='E-mail nadawcy')),
                ('email_subject', models.CharField(default='Twoje Atelier - Potwierdzenie zamówienia nr {order_id}', max_length=200, verbose_name='Temat e-maila')),
                ('email_message', models.TextField(default='Witaj {first_name},\n\nDziękujemy za zakupy w Atelier!\nTwoje zamówienie nr {order_id} zostało pomyślnie opłacone.\n\nJeśli kupiłaś pliki cyfrowe, możesz je pobrać bezpośrednio ze strony potwierdzenia.\n\nNiech magia będzie z Tobą!', help_text='Możesz użyć tagów: {order_id} oraz {first_name}, system automatycznie podmieni je na dane z zamówienia.', verbose_name='Treść e-maila')),
            ],
            options={
                'verbose_name': 'Ustawienia E-mail',
                'verbose_name_plural': 'Ustawienia E-mail',
            },
        ),
    ]
